### ISSUE TITLE
POST "/api/v1/users/:id/good_deeds"

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_api#13]
## GoodDeedsController#Create

Request: `POST "/api/v1/users/:id/good_deeds"`
Request Body:
```
{:data=>
  {:id=>"374",
   :type=>"good_deeds_create",
   :attributes=>
    {:name=>"Wash neighbor's car.",
     :media_link=>nil,
     :notes=>nil,
     :date=>"2023-01-01",
     :time=>"2000-01-01T17:00:00.000Z",
     :status=>"In Progress",
     :host_id=>1026}}}}
```
---
Response:
Status: 201
---
When I send a POST request with the included body to the endpoint, I receive:

- [X] A status 201

## Sad Path
When I send a POST request without all the information in the body, I receive:

- [X] A status 400 or 404
- [X] An error object
```
{
  "errors": [
    {
      "status": "400"
      "title": "Invalid Request",
      "detail": [
        "Validation failed: Date can't be blank"
         ]
     }
   ]
}
```

**Comment by MelTravelz** [comment]
Need to update "deed_name" to "name"
