### ISSUE TITLE
PATCH "/api/v1/users/:user_id/good_deeds/:good_deed_id"

### ISSUE THREAD

**Issue by hamouj** [do-good-2211/do_good_api#16]
## GoodDeedsController#Update

Request: `PATCH "/api/v1/users/:user_id/good_deeds/:good_deed_id"`
Body:
```
{
  "date": "02-02-2024",
  "time": "2000-01-01T16:00:00.000Z",
  "status": "Completed",
  "media_link": "http://neverland.io/mermaids",
  "notes": "OMG, can't believe we high-fived mermaids today!",
  "attendees": [{"user_id": 1}, {"user_id": 2}]
 }
```
---
Response:
Status: 201
---
When I send aPATCH request with the included body to the endpoint, I receive:

- [ ] A status 202

## Sad Path
If the user does not exist **or** the good deed does not exist, I receive

- [ ] A status 404
- [ ] An error object
```
{
  "errors": [
    {
      "status": "404"
      "title": "Invalid Request",
      "detail": [
        "Couldn't find User with 'id'=<id>"
         ]
     }
   ]
}
```

**Comment by MelTravelz** [comment]
**Updates Needed:** 

- Request body does NOT need to return the deed name but DOES need to return the status
